import type { Track } from "../types";

export const defaultTracks: Track[] = [
	{
		id: "bengali-folk-1",
		title: "Ami Banglay Gaan Gai",
		artist: "Folk Fusion Revival",
		album: "Bangla Sonority",
		duration: 180,
		url: "synth://chill",
		artwork: "linear-gradient(135deg, #020024 0%, #090979 35%, #00d4ff 100%)", // Electric Teal Glow
		genre: "Bengali Folk",
		mood: "Chill",
		bengaliTitle: "আমি বাংলায় গান গাই",
		bengaliArtist: "ফোক ফিউশন রিভাইভাল",
		isFavorite: true,
		addedAt: "2026-05-27T12:00:00Z",
		playCount: 12,
		skipCount: 0,
		lyrics: [
			{ time: 0, text: "আমি বাংলায় গান গাই..." },
			{ time: 10, text: "আমি বাংলার গান গাই..." },
			{ time: 20, text: "আমি আমার আমিকে চিরদিন এই বাংলায় খুঁজে পাই।" },
			{ time: 30, text: "আমি বাংলায় দেখি স্বপ্ন..." },
			{ time: 40, text: "আমি বাংলায় বাঁধি সুর..." },
			{ time: 50, text: "আমি এই বাংলার ধুলিমাটি মেখে হেঁটে যাই বহুদূর।" },
		],
	},
	{
		id: "bengali-classic-2",
		title: "Coffee Houser Sei Addata",
		artist: "Classic Tribute Ensemble",
		album: "Nostalgia Unplugged",
		duration: 210,
		url: "synth://ambient",
		artwork: "linear-gradient(135deg, #4b0082 0%, #1a0033 50%, #8b008b 100%)", // Neo Purple Burst
		genre: "Retrospective",
		mood: "Sad",
		bengaliTitle: "কফি হাউজের সেই আড্ডাটা",
		bengaliArtist: "ক্লাসিক ট্রিবিউট এনসেম্বল",
		isFavorite: false,
		addedAt: "2026-05-27T12:05:00Z",
		playCount: 8,
		skipCount: 1,
		lyrics: [
			{ time: 0, text: "কফি হাউজের সেই আড্ডাটা আজ আর নেই..." },
			{ time: 10, text: "আজ আর নেই..." },
			{ time: 20, text: "কোথায় হারিয়ে গেল সোনালী বিকেলগুলো সেই..." },
			{ time: 30, text: "আজ আর নেই।" },
			{ time: 40, text: "নিখিলেশ প্যারিসে, মইদুল ঢাকাতে..." },
			{ time: 50, text: "নেই তো কেউ কোথাও আজ যেন নেই।" },
		],
	},
	{
		id: "lofi-beats-3",
		title: "Midnight Dhaka Lofi Cafe",
		artist: "Dhaka Study Beats",
		album: "Exam Cram 101",
		duration: 150,
		url: "synth://focus",
		artwork: "linear-gradient(135deg, #111111 0%, #2a005c 40%, #0052cc 100%)", // Ultra AMOLED Deep Blue
		genre: "Lofi / Ambient",
		mood: "Focus",
		bengaliTitle: "মাঝরাত ঢাকা লফি ক্যাফে",
		bengaliArtist: "ঢাকা স্টাডি বিটস",
		isFavorite: true,
		addedAt: "2026-05-27T12:10:00Z",
		playCount: 25,
		skipCount: 2,
		lyrics: [
			{ time: 0, text: "Relaxing custom synthesizer soundstage..." },
			{ time: 10, text: "Perfect for midnight project writing & exam prep." },
			{ time: 20, text: "Equalizer responsive audio wave active..." },
			{ time: 30, text: "Feel the deep off-grid stereo vibration." },
			{ time: 40, text: "Continuous sound loops generating offline." },
		],
	},
	{
		id: "bengali-baul-4",
		title: "Mon Re Krishi Kaj Jano Na",
		artist: "Sufi & Baul Electronica",
		album: "Soul Soil Echoes",
		duration: 160,
		url: "synth://energy",
		artwork: "linear-gradient(135deg, #fc466b 0%, #3f5efb 100%)", // Neon Pink Electric Grid
		genre: "Sufi Folk",
		mood: "Energy",
		bengaliTitle: "মন রে কৃষি কাজ জানো না",
		bengaliArtist: "সুফি ও বাউল ইলেক্ট্রনিকা",
		isFavorite: false,
		addedAt: "2026-05-27T12:15:00Z",
		playCount: 19,
		skipCount: 3,
		lyrics: [
			{ time: 0, text: "মন রে কৃষি কাজ জানো না..." },
			{ time: 10, text: "এমন মানব জমিন রইল পতিত," },
			{ time: 20, text: "আবাদ করলে ফলতো সোনা।" },
			{ time: 30, text: "গুরু রোপণ করেছেন বীজ..." },
			{ time: 40, text: "তাতে ভক্তি সেচ দিলে ফলতো সোনা।" },
		],
	},
	{
		id: "bengali-patriotic-5",
		title: "Amar Sonar Bangla",
		artist: "National Instrumental",
		album: "Folk Heritage",
		duration: 120,
		url: "synth://ambient",
		artwork: "linear-gradient(135deg, #134e5e 0%, #71b280 100%)", // Golden Bengal Green/Gold Glow
		genre: "Acoustic",
		mood: "Happy",
		bengaliTitle: "আমার সোনার বাংলা",
		bengaliArtist: "জাতীয় ইন্সট্রুমেন্টাল",
		isFavorite: true,
		addedAt: "2026-05-27T12:20:00Z",
		playCount: 30,
		skipCount: 0,
		lyrics: [
			{ time: 0, text: "আমার সোনার বাংলা, আমি তোমায় ভালোবাসি।" },
			{ time: 10, text: "চিরদিন তোমার আকাশ, তোমার বাতাস," },
			{ time: 20, text: "আমার প্রাণে বাজায় বাঁশি।" },
			{ time: 30, text: "ও মা, ফাল্গুনে তোর আমের বনে ঘ্রাণে পাগল করে..." },
			{ time: 40, text: "ও মা, অঘ্রাণে তোর ভরা ক্ষেতে আমরা কি দেখেছি মধুর হাসি।" },
		],
	},
];
